### PR TITLE
Atlas metadata print out

### PR DESCRIPTION
**Pull request by FedeClaudi**
Okay so I've added a `__rich_console__` method to the `BGAtlas` class, that's what's used by rich's `Console` for printing objects. If users use the builtin `print` function than `__str__` will be used instead, which prints the same but without colors. 

This is what it looks like:
image

and with the normal print
image

and `__repr__` returns: 
image

### CODE REVIEW

**Comment by nickdelgrosso** [comment]
Wow, looks great!

**Review by adamltyson — APPROVED** [review]

**Review by vigji — COMMENTED** [review]
Nice, looks good to me!

The only things I would raise is that 
1. Probably we want this to go in the atlas Core class, for it to be available also for custom atlases from local data - all info should be available;
2. Maybe it's a bit lot of "cosmetic" code to go in the main data-centric class, and could be refactored out in an utility function; but this is entirely subjective, and I'm happy to keep it this way and maybe move it later, it's a really minor change.

They're beautiful!

**Comment by FedeClaudi** [comment]
Sure, I can move it to a function no problem

**Comment by FedeClaudi** [comment]
aight, moved the `__` methods to `Core` and the bulk of the `rich` code to a utility function

**Review by vigji — APPROVED** [review]
Great! Good for me to merge, thanks for this!

**Pull request merged**
