### PR TITLE
Optimize `get_structure_mask` for structures with many children

### PR DESCRIPTION
**Pull request by sdiebolt**
`get_structure_mask` can be optimized for structures with many children: see #119.

Thanks so much for creating and maintaining this awesome package! I'm not yet used to contributions on GitHub, feel free to let me know if I can improve anything.

### CODE REVIEW

**Comment by vigji** [comment]
@FedeClaudi @adamltyson tests are running fine locally on my machine, but there seems to be something funky in GitHub actions going on - would you agree to merge and fix tests in a separate PR?

**Comment by FedeClaudi** [comment]
I'm happy with it

**Comment by sdiebolt** [comment]
It seems like the fail comes from the dependency resolver: it should not have anything to do with the changes from this PR. 

You might also want to try running the tests again: as the dependencies didn't change since last commit, it might either be a one-time bug from `pip`, or a problem introduced by a new version of one of the dependencies (in which case you might want to try to be more strict in `requirements.txt`?).

**Comment by sdiebolt** [comment]
Still there after a rerun... I just tried running `pip install .[dev]` on my machine with Python 3.8.12 (as defined in the GitHub Actions workflow) and there is indeed a lot of [backtracking](https://pip.pypa.io/en/stable/topics/dependency-resolution/#possible-ways-to-reduce-backtracking). I think this could be solved very simply by setting stricter version limits in `requirements.txt`!

Changing `requirements.txt` is best left to someone who is more aware of the exact use of each of those dependencies in BG-AtlasAPI, but do tell me if I can help. :slightly_smiling_face:

**Comment by vigji** [comment]
Yes it's definitively not on you @sdiebolt to fix! I'll try to give it a shot in the next days

**Comment by adamltyson** [comment]
Having looked at this again, sorry @sdiebolt, you're right, the tests failing is nothing at all to do with this PR, we should merge this now, and fix the test failure separately.

**Comment by sdiebolt** [comment]
No problem, that is indeed a weird test failure!

**Comment by adamltyson** [comment]
@vigji are we good to merge? I haven't tested this myself yet.

**Pull request merged**
