### PR TITLE
brainglobe command

### PR DESCRIPTION
**Pull request by FedeClaudi**
I've unified all command line commands under a single command, as suggested by @adamltyson 

Now you can just use `brainglobe` followed by
* `list` to print all atlases
* `update` with `-a atlas_name -f` to update and atlas (`-f` forces the update)
* `install` with `-a atlas_name` to install a new atlas
* `config` to modify the config.

### CODE REVIEW

**Comment by FedeClaudi** [comment]
not sure why the commit history is so long, it should be only the last 2...

**Comment by adamltyson** [comment]
> not sure why the commit history is so long, it should be only the last 2...

I think this is usually when you continue to work on a branch, that's previously been merged. It's not even with master because of the merge commit. I think you can either make a new branch, or merge master into your branch.

**Comment by FedeClaudi** [comment]
I did merge master?

image

**Comment by adamltyson** [comment]
> I did merge master?

No idea then, sorry.

**Comment by adamltyson** [comment]
Also this is great, somehow much more professional.

> update with -a atlas_name -f to update and atlas (-f forces the update)
install with -a atlas_name to install a new atlas

What happens if you don't use the `-a` flag? Does it update  all atlases, or can we get rid of it?

**Comment by FedeClaudi** [comment]
if you don't use `-a` it throws an error because you didn't pass any atlas name.

**Comment by adamltyson** [comment]
Oh sorry, I meant is there any functionality without it? Or can we just do `brainglobe install atlas_name`?

**Comment by FedeClaudi** [comment]
yeah `list` and `config` don't take `atlas_name` as arguments so I think to remove `-a` with `click` I would have to make it so that you always have to pass a name. Maybe @vigji knows better how to do this?

**Comment by adamltyson** [comment]
Ahh i didn't know you were using click. In that case dw. It's not a priority

**Comment by vigji** [comment]
I am not an expert, but maybe these groups can be helpful in this context? https://click.palletsprojects.com/en/7.x/commands/

**Comment by FedeClaudi** [comment]
I only skimmed through it, but I think for now it;s good as is. Should we merge?

**Comment by adamltyson** [comment]
Yep, I think this is good to merge whenever.

**Pull request merged**
