### PR TITLE
Updating pbar and a couple other things

### PR DESCRIPTION
**Pull request by FedeClaudi**

### CODE REVIEW

**Comment by FedeClaudi** [comment]
@vigji  opened a cleaner PR here, if the tests pass we can merge?

**Comment by FedeClaudi** [comment]
I've decided not to include pycln at the end because it would sometimes not work nicely with the other pre-commit checks and it was more bother than benefit...

**Review by vigji — APPROVED** [review]
Good for me as soon as tests are fixed!

**Comment by FedeClaudi** [comment]
It seems that the linting is failing, but both black and flake8 pass on my machine. 
Any idea how to fix?

**Comment by vigji** [comment]
uhm, trying updating black? I was also having something funny with
black-ing of that file...

**Comment by adamltyson** [comment]
Yeah, I think it's a black version issue. We should probably update the version in  `.pre-commit-config.yaml` too.

**Comment by FedeClaudi** [comment]
Done, now black did some stuff to list_atlases, le's see if that fixed it

**Comment by FedeClaudi** [comment]
That fixed it, merging now.

**Pull request merged**
