### PR TITLE
JOSS submission

### PR DESCRIPTION
**Pull request by adamltyson**
Hi @FedeClaudi, @vigji,

I've put together a very rough draft of the JOSS submission to get the conversation started. There are guidelines [here](https://joss.readthedocs.io/en/latest/submitting.html), and you can see how it compiles [here](https://whedon.theoj.org/).

### CODE REVIEW

**Comment by FedeClaudi** [comment]
Haven't read through the content, but the format looks good. 
Only the footer has something missing:
image

**Comment by adamltyson** [comment]
>  Only the footer has something missing:

I'm not sure how we fix that. It may only get fixed with the final submission? You have to fill in a form which may supply those details.

**Comment by FedeClaudi** [comment]
I've made some edits, but feel free to ignore/include any of it. The only thing I think it's worth changing is this paragram (right under the header **statement of need**:
>Neuroscience is gradually becoming a field reliant on large scale data acquisition, such as whole-brain optical neural recordings [@Ahrens:2012], brain-wide connectivity mapping [@Osten:2013] or high-density electrophysiological probes [@Jun:2017]. For this reason, custom, computational analysis is now necessary in the majority of neuroscience laboratories, and Python is emerging as the programming language of choice [@Muller:2015].


It doesn't really add much, the only relevant part is the fact that python is becoming the most adopted language, but we can mention that elsewhere. I would start talking about atlases, what they are and how useful they are. Then say that the problem of the APIs and justify why we made BG (and we can add a sentence here about why python). 

What do you guys think?

**Comment by adamltyson** [comment]
< It doesn't really add much, the only relevant part is the fact that python is becoming the most adopted language, but we can mention that elsewhere. I would start talking about atlases, what they are and how useful they are. Then say that the problem of the APIs and justify why we made BG (and we can add a sentence here about why python).

What do you guys think?

Agree, it's waffle. I've removed that paragraph, and slotted in the Python bit into the next paragraph.

**Comment by FedeClaudi** [comment]
cool, it looks good to me! Is this really all we have to do for submission? Awesome!

**Comment by adamltyson** [comment]
> cool, it looks good to me! Is this really all we have to do for submission? Awesome!

Pretty much, there's just a form to fill in. 

Once @vigji has had a chance to take a look (take your time), I'll send it around the senior authors.

**Comment by FedeClaudi** [comment]
@vigji `brainrender` is just `brainrender`, not `BrainRender` (it used to be like this but now it's just lower case), but thanks for checking it 👍 

The other changes also look good.

**Review by vigji — COMMENTED** [review]
I would also add some reference for the idea of morphing stuff to a common reference (maybe amap, or for zebrafish https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4710481/) if that is fine

**Comment by adamltyson** [comment]
Looks good to me. @FedeClaudi are you happy to approve this? If so I'll send it round tomorrow.

**Review by FedeClaudi — APPROVED** [review]

**Comment by vigji** [comment]
I can't preview it (page not found when trying it), is it my browser or I broke something in the md file?

**Comment by adamltyson** [comment]
>  I can't preview it (page not found when trying it), is it my browser or I broke something in the md file?

I think the server might have been down. It didn't work for me earlier, but it's working now. I'll send it around later.

**Comment by FedeClaudi** [comment]
I've added in `docs/md` automatically generated docs with `pydoc2md`. The docstrings seem to be there and it seems to have worked fine (e.g. the link to github work correctly etc). Have a look and lets see if you want to add it to the gitbook

**Comment by adamltyson** [comment]
Yeah that looks good to go onto gitbook. One thing - the `summary.md` has links to your local machine. Can you get `pydoc2md` to make these relative, or shall we just edit them manually?

**Comment by FedeClaudi** [comment]
should be fixed now

**Comment by vigji** [comment]
I integrated Ruben's comments in the text, let me know what you think!

**Comment by FedeClaudi** [comment]
looks good. 

I made some changes, mostly to the first part of the summary. Trying to say the same thing with different words.. we can choose which ever (mine is maybe a bit lengthy).

**Comment by adamltyson** [comment]
I think I _just_ prefer Fede's edits. Some tiny comments:
* I don't like the use of "clarifying". Mostly because it makes me think of CLARITY tissue clearing
* I'm not sure most atlases do come with an API. The majority of the ones I've used don't (thinking of the many MRI ones).

**Comment by FedeClaudi** [comment]
Okay, we can fix those two points, the make sense.

**Comment by vigji** [comment]
I also prefer yours and agree on Adam's points?

**Comment by FedeClaudi** [comment]
added in @adamltyson 's suggestions. Should we send it around for another round of PI feedback?
as far as I'm concerned is good for submission :)

**Comment by vigji** [comment]
Good for me as well!

**Comment by FedeClaudi** [comment]
Do we know why the tests stopped working? It seems to be something with lint.

**Comment by FedeClaudi** [comment]
Suggestions.

1. In `statement of need` paragraph 1 when we say that the neuroscience community benefits from the atlases we could mention open-science datasets that were only possible **because** of these atlases (e.g. mouse light) [though of course this is not the only way in which they've been useful].

2. In `statement of need` paragraph 2, when we mention 2 atlases and say that they come with APIs, we should also mention that e.g. the allen atlas comes with dedicated software that can be used without any coding experience. However what you can do with this software is limited hence APIs. However learning how to use APIs is time consuming (one per atlas.. ) so we made a single APIs which is easy and universal.

Question: 
Does anyone know of an atlas like we have for the brain for other organs?

**Comment by vigji** [comment]
> Do we know why the tests stopped working? It seems to be something with lint.

Gosh, I might have messed up with my local branches and merged here a bunch of commits...what's best? Should I open a new joss branch with just the paper? Or we can merge only that to master once we're done

**Comment by vigji** [comment]
> 1. In `statement of need` paragraph 1 when we say that the neuroscience community benefits from the atlases we could mention open-science datasets that were only possible **because** of these atlases (e.g. mouse light) [though of course this is not the only way in which they've been useful].
> 2. In `statement of need` paragraph 2, when we mention 2 atlases and say that they come with APIs, we should also mention that e.g. the allen atlas comes with dedicated software that can be used without any coding experience. However what you can do with this software is limited hence APIs. However learning how to use APIs is time consuming (one per atlas.. ) so we made a single APIs which is easy and universal.

Agree with both suggestions!

> Question:
> Does anyone know of an atlas like we have for the brain for other organs?

I haven't googled too hard but I can't find any! Maybe @adamltyson knows more

**Comment by adamltyson** [comment]
Also agree with the suggestions. 

I don't know of any other atlases. I always assumed there must be, but I suppose other organs aren't imaged as much, and don't have the same complexity. (I'm sure someone could correct me on this neuro-centric point of view).

**Comment by FedeClaudi** [comment]
added them in, let me know what you think. 

> Gosh, I might have messed up with my local branches and merged here a bunch of commits...what's best? Should I open a new joss branch with just the paper? Or we can merge only that to master once we're done

I think that's fine, we don't have to merge this branch at any point, right @adamltyson ?

**Comment by adamltyson** [comment]
> I think that's fine, we don't have to merge this branch at any point, right @adamltyson ?

I don't think so, see here:

> Your paper (paper.md and BibTeX files, plus any figures) must be hosted in a Git-based repository together with your software (although they may be in a short-lived branch which is never merged with the default).

However, presumably we want the paper and the code being reviewed to be in the same branch? So effectively we do have to at least merge master into joss (if not the other way around).

**Comment by vigji** [comment]
In sentence
> These atlases are used throughout neuroscience, for teaching, visualisation of data, and registration of imaging data to a common coordinate space.

I'd say we either cite a lot of stuff, or don't cite anything

**Comment by adamltyson** [comment]
> I'd say we either cite a lot of stuff, or don't cite anything

We don't cite anything at the moment, right?

**Comment by vigji** [comment]
> We don't cite anything at the moment, right?

There was a zebrafish paper, but it did not make sense in an isolated way and it was referring to an outdated Atlas so I removed it. I can chip in with one or two papers on zebrafish morphing if we decide to cite, but I don't know what are the most common references on the whole atlas business

**Comment by adamltyson** [comment]
I think I would stick to no references, otherwise we will end up citing 5-6 papers.

**Comment by FedeClaudi** [comment]
Do you think we should mention the atlas generation stuff in the paper?

**Comment by vigji** [comment]
Probably a sentence or two, yes! Just to specify to what exactly we provide an API for

**Comment by vigji** [comment]
I can take care of this

**Comment by vigji** [comment]
Good for me now, let me know!

**Comment by vigji** [comment]
Perfect! @adamltyson looks good to you?

**Comment by adamltyson** [comment]
Yep!

**Comment by adamltyson** [comment]
I converted to draft, so we (I) don't accidentally merge into master.

**Comment by adamltyson** [comment]
I guess we can close this PR now?

**Comment by vigji** [comment]
guess so yes!

**Comment by adamltyson** [comment]
Closing now the paper is published.

**Pull request closed without merging**
